name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Insert API Key 🔑
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          sed -i 's/const apiKey = "YOUR_API_KEY_PLACEHOLDER";/const apiKey = "'$OPENAI_API_KEY'";/' script.js

      - name: Build
        run: |
          # Add any build commands here if needed
          # For a simple static site, we can just create a dummy file
          echo "Build step" > build.txt

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          force: true
